### PR TITLE
Add x-readme-source header

### PR DESCRIPTION
**Pull request by mjcuva**
Add header to tell ReadMe that the synced file is coming from the cli

### CODE REVIEW

**Comment by erunion** [comment]
@mjcuva This LGTM. Do we need to wait for the `cli` header support in the app to get into prod before releasing this?

**Comment by domharrington** [comment]
I don't think it'll have any adverse affects if this gets released before that gets merged. Right now it just defaults to `cli`.

**Comment by gratcliff** [comment]
@domharrington is correct, it's hardcoded in `dash/api/v1/api-specification` right now at the base `POST` request.

**Comment by erunion** [comment]
Confirmed! Merging and tagging a new release.

**Pull request merged**
