### PR TITLE
chore(deps): upgrading out of date deps

### PR DESCRIPTION
**Pull request by erunion**
#### Before

```
Package                          Current  Wanted  Latest  Location                                      Depended by
@commitlint/cli                   17.6.5  17.6.6  17.6.6  node_modules/@commitlint/cli                  rdme
@commitlint/config-conventional   17.6.5  17.6.6  17.6.6  node_modules/@commitlint/config-conventional  rdme
@readme/eslint-config             10.6.0  10.6.1  10.6.1  node_modules/@readme/eslint-config            rdme
chalk                              4.1.2   4.1.2   5.3.0  node_modules/chalk                            rdme
configstore                        5.0.1   5.0.1   6.0.0  node_modules/configstore                      rdme
eslint                            8.42.0  8.44.0  8.44.0  node_modules/eslint                           rdme
jest                              29.5.0  29.6.0  29.6.0  node_modules/jest                             rdme
jest-extended                      3.2.4   3.2.4   4.0.0  node_modules/jest-extended                    rdme
node-fetch                        2.6.11  2.6.12   3.3.1  node_modules/node-fetch                       rdme
oas                               20.8.4  20.8.7  20.8.7  node_modules/oas                              rdme
open                               8.4.2   8.4.2   9.1.0  node_modules/open                             rdme
ora                                5.4.1   5.4.1   6.3.1  node_modules/ora                              rdme
prettier                           2.8.8   2.8.8   3.0.0  node_modules/prettier                         rdme
semver                             7.5.1   7.5.3   7.5.3  node_modules/semver                           rdme
simple-git                        3.19.0  3.19.1  3.19.1  node_modules/simple-git                       rdme
ts-jest                           29.1.0  29.1.1  29.1.1  node_modules/ts-jest                          rdme
type-fest                         3.11.1  3.12.0  3.12.0  node_modules/type-fest                        rdme
typescript                         5.1.3   5.1.6   5.1.6  node_modules/typescript                       rdme
```

#### After
```
Package      Current  Wanted  Latest  Location                  Depended by
chalk          4.1.2   4.1.2   5.3.0  node_modules/chalk        rdme
configstore    5.0.1   5.0.1   6.0.0  node_modules/configstore  rdme
node-fetch    2.6.12  2.6.12   3.3.1  node_modules/node-fetch   rdme
open           8.4.2   8.4.2   9.1.0  node_modules/open         rdme
ora            5.4.1   5.4.1   6.3.1  node_modules/ora          rdme
prettier       2.8.8   2.8.8   3.0.0  node_modules/prettier     rdme
```

### CODE REVIEW

**Comment by erunion** [comment]
Looks like the `eslint-plugin-jest-dom` is no longer getting installed on Node 14. Maybe it's okay to stop linting on Node 14 since it's EOL?

**Comment by kanadgupta** [comment]
@erunion it looks like `eslint-plugin-jest-dom` made `@testing-library/dom` a required peer dep when bumping to v5: https://github.com/testing-library/eslint-plugin-jest-dom/releases/tag/v5.0.0

I'm guessing there's something about the dep resolution in npm@8 and above where they automatically handle this, but would it be too much to bring `@testing-library/dom` into the fold in `@readme/eslint-config`?

**Comment by erunion** [comment]
Ah that's happening because Node 14 still ships NPM 6 which doesn't install peerDeps by default. They changed that with NPM 7. What if we did an `if` block in the CI workflow for Node 14 to install NPM 7?

**Review by kanadgupta — APPROVED** [review]
@erunion ended up getting it working by backfilling the `@testing-library/dom` peerdep. I like this approach better since I don't want us to have to deal with possible installation issues for Node 14 users and forcing them to upgrade their npm version. Merging!

**Pull request merged**
